/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/attendance/bulk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description PUT /api/attendance/bulk/ — atomic upsert for one group+date. */
        put: operations["attendance_bulk_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendance/roster/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/attendance/roster/ — full group roster merged with saved rows. */
        get: operations["attendance_roster_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendance/week/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/attendance/week/ — Mon–Fri matrix for one group. */
        get: operations["attendance_week_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendance/week/bulk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description PUT /api/attendance/week/bulk/ — atomic status upsert for Mon–Fri; notes preserved. */
        put: operations["attendance_week_bulk_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Anonymous GET that sets the `csrftoken` cookie (design "dedicated
         *     GET /api/auth/csrf/"). Must stay reachable pre-login: `/me/` is
         *     IsAuthenticated and cannot bootstrap CSRF for the login call itself.
         */
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Session login (identity-auth spec — "Session Login/Logout/Me
         *     Endpoints"). No JWT: this establishes the standard Django session
         *     cookie via `django.contrib.auth.login`.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Clears the current session server-side. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the current authenticated user's identity. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/personas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists the personas the picker offers. */
        get: operations["demo_personas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates a `pending` receipt and hands provisioning to the worker. */
        post: operations["demo_sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/sessions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Reports session status and, once ready, signs the guest in.
         *
         *     Sign-in lives on the poll rather than on a separate endpoint so that
         *     re-opening a session URL later just re-signs into the same workspace —
         *     provisioning never runs twice (paysys `SessionsController#show`).
         */
        get: operations["demo_sessions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["groups_list"];
        put?: never;
        post: operations["groups_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["groups_retrieve"];
        put: operations["groups_update"];
        post?: never;
        delete: operations["groups_destroy"];
        options?: never;
        head?: never;
        patch: operations["groups_partial_update"];
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson-plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lesson_plans_list"];
        put?: never;
        post: operations["lesson_plans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson-plans/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lesson_plans_retrieve"];
        put?: never;
        post?: never;
        delete: operations["lesson_plans_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson-plans/{id}/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/lesson-plans/<id>/export?format=docx|md (ai-planeaciones
         *     spec — "Ready LessonPlan Can Be Exported as Docx or Markdown").
         *
         *     Only a `ready` plan may be exported; `pending`/`failed` are rejected
         *     (no partial/empty document is ever returned).
         */
        get: operations["lesson_plans_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson-plans/catalog/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lesson_plans_catalog_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson-plans/fields/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/lesson-plans/fields/ — every formative field of the
         *     curriculum, in catalog order.
         *
         *     Deliberately not folded into `catalog`: `catalog` needs a field id to
         *     answer, and the picker that supplies it has to be rendered first. Every
         *     field is listed, including the two with no verified content yet — the
         *     form keeps them selectable behind an empty state rather than pretending
         *     they do not exist.
         *
         *     Named `formative_fields` with an explicit `url_path` so the method does
         *     not shadow anything named `fields` on the view.
         */
        get: operations["lesson_plans_fields_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lesson-plans/quota/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/lesson-plans/quota/ — the monthly allowance of the active
         *     workspace ("Generaciones de este mes").
         *
         *     Deliberately not folded into `catalog`: the card is rendered before
         *     the teacher has picked a group or a field, and `catalog` requires
         *     both. Reading is side-effect free — `current_usage` reports an absent
         *     ledger row as `0` instead of seeding one, so merely opening the form
         *     never writes.
         */
        get: operations["lesson_plans_quota_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzy/chat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/quizzy/chat/ — Composer turn + persist conversation. */
        post: operations["quizzy_chat_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzy/conversations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/quizzy/conversations/ — owner's threads in active workspace. */
        get: operations["quizzy_conversations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzy/conversations/{conversation_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/PATCH/DELETE /api/quizzy/conversations/<id>/. */
        get: operations["quizzy_conversations_retrieve"];
        put?: never;
        post?: never;
        /** @description GET/PATCH/DELETE /api/quizzy/conversations/<id>/. */
        delete: operations["quizzy_conversations_destroy"];
        options?: never;
        head?: never;
        /** @description GET/PATCH/DELETE /api/quizzy/conversations/<id>/. */
        patch: operations["quizzy_conversations_partial_update"];
        trace?: never;
    };
    "/api/school-years/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["school_years_list"];
        put?: never;
        post: operations["school_years_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/school-years/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["school_years_retrieve"];
        put: operations["school_years_update"];
        post?: never;
        delete: operations["school_years_destroy"];
        options?: never;
        head?: never;
        patch: operations["school_years_partial_update"];
        trace?: never;
    };
    "/api/schools/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schools_list"];
        put?: never;
        post: operations["schools_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schools/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schools_retrieve"];
        put: operations["schools_update"];
        post?: never;
        delete: operations["schools_destroy"];
        options?: never;
        head?: never;
        patch: operations["schools_partial_update"];
        trace?: never;
    };
    "/api/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["students_list"];
        put?: never;
        post: operations["students_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["students_retrieve"];
        put: operations["students_update"];
        post?: never;
        delete: operations["students_destroy"];
        options?: never;
        head?: never;
        patch: operations["students_partial_update"];
        trace?: never;
    };
    "/api/workspaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaces_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AttendanceBulkEntry: {
            student: number;
            status: components["schemas"]["Status148Enum"];
            /** @default  */
            notes: string;
        };
        AttendanceBulkRequest: {
            group: number;
            /** Format: date */
            date: string;
            entries: components["schemas"]["AttendanceBulkEntry"][];
        };
        AttendanceBulkResponse: {
            saved: number;
        };
        AttendanceRosterEntry: {
            student: number;
            first_name: string;
            last_name_paternal: string;
            curp: string;
            status: components["schemas"]["Status148Enum"];
            notes: string;
        };
        AttendanceWeekBulkEntry: {
            student: number;
            /** Format: date */
            date: string;
            status: components["schemas"]["Status148Enum"];
        };
        AttendanceWeekBulkRequest: {
            group: number;
            /** Format: date */
            week_start: string;
            entries: components["schemas"]["AttendanceWeekBulkEntry"][];
        };
        AttendanceWeekResponse: {
            /** Format: date */
            week_start: string;
            dates: string[];
            students: components["schemas"]["AttendanceWeekStudent"][];
        };
        AttendanceWeekStudent: {
            student: number;
            first_name: string;
            last_name_paternal: string;
            days: {
                [key: string]: "present" | "absent" | "late" | "excused";
            };
        };
        /** @description An official content with its verified learning processes. */
        CatalogContent: {
            readonly id: string;
            readonly text: string;
            readonly pdas: components["schemas"]["CatalogPda"][];
        };
        /** @description A curriculum formative field (`campo formativo`). */
        CatalogField: {
            readonly id: string;
            readonly name: string;
        };
        /** @description The automatic group context shown by the planning form. */
        CatalogGroup: {
            readonly id: number;
            readonly label: string;
            readonly grade: number;
            readonly school_name: string;
            readonly school_cct: string;
            readonly school_year_label: string;
        };
        /** @description The official Phase 6 planning methodology. */
        CatalogMethodology: {
            readonly id: string;
            readonly name: string;
        };
        /** @description A verified learning process (`PDA`) of an official content. */
        CatalogPda: {
            readonly id: string;
            readonly text: string;
        };
        /** @description A subject belonging to a formative field. */
        CatalogSubject: {
            readonly id: string;
            readonly name: string;
            readonly field_id: string;
        };
        /** @description The requesting teacher's identity. */
        CatalogTeacher: {
            /** Format: email */
            readonly email: string;
        };
        /** @description A cross-cutting theme (`eje articulador`). */
        CatalogTheme: {
            readonly id: string;
            readonly name: string;
        };
        /** @description One official content from the grounding snapshot plus its PDAs. */
        ContentPdaText: {
            content: string;
            pdas: string[];
        };
        /** @description One official content plus the PDAs chosen under it. */
        ContentSelection: {
            content_id: string;
            pda_ids: string[];
        };
        ConversationDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly agent_id: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly messages: components["schemas"]["Message"][];
        };
        ConversationList: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly agent_id: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description The provisioning receipt as the polling client sees it.
         *
         *     `workspace` and `email` are null until the session is `ready`;
         *     `error_message` is empty unless it `failed`.
         */
        DemoSession: {
            /** Format: uuid */
            readonly id: string;
            readonly persona: string;
            readonly status: components["schemas"]["Status95aEnum"];
            /** Format: uuid */
            readonly workspace: string | null;
            readonly email: string | null;
            readonly error_message: string;
        };
        /**
         * @description Validates the requested persona against the registry.
         *
         *     Rejecting an unknown key here (400) rather than in the task keeps a
         *     guaranteed-to-fail session from ever being written.
         */
        DemoSessionCreate: {
            persona: components["schemas"]["PersonaEnum"];
        };
        /**
         * @description Full payload of `GET /api/lesson-plans/quota/` (the "Generaciones de
         *     este mes" card).
         *
         *     `remaining` is served rather than left to the client: it is floored at
         *     zero, and a lowered `LESSON_PLAN_MONTHLY_GENERATION_LIMIT` can leave a
         *     workspace above its own allowance, where `limit - used` would render as
         *     a negative countdown.
         */
        GenerationQuota: {
            readonly period: string;
            readonly used: number;
            readonly limit: number;
            readonly remaining: number;
        };
        Group: {
            readonly id: number;
            school_year: number;
            grado: number;
            grupo: string;
            /** Format: uuid */
            readonly workspace: string;
        };
        LessonPlan: {
            readonly id: number;
            /** Format: uuid */
            readonly workspace: string;
            group: number;
            campo: string;
            grade: string;
            theme: string;
            readonly field_id: string;
            readonly subject_id: string;
            readonly methodology_id: string;
            readonly duration_weeks: number | null;
            /** Format: date */
            readonly start_date: string | null;
            /** Format: date */
            readonly end_date: string | null;
            readonly scenario: components["schemas"]["ScenarioEnum"];
            readonly context_diagnosis: string;
            readonly cross_cutting_theme_ids: string[];
            readonly content_selections: components["schemas"]["ContentSelection"][];
            readonly title: string;
            readonly proyecto: unknown;
            readonly status: components["schemas"]["Status95aEnum"];
            readonly failure_reason: string;
            readonly provider: string;
            readonly model_name: string;
            readonly prompt_tokens: number | null;
            readonly completion_tokens: number | null;
            readonly invented_pdas: boolean;
            readonly invented_pda_texts: string[];
            readonly grounding_selections: components["schemas"]["ContentPdaText"][];
            /** Format: date-time */
            readonly generated_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Full payload of `GET /api/lesson-plans/catalog/`. */
        LessonPlanCatalog: {
            readonly phase: number;
            readonly grade: number;
            readonly field: components["schemas"]["CatalogField"];
            readonly methodology: components["schemas"]["CatalogMethodology"];
            readonly subjects: components["schemas"]["CatalogSubject"][];
            readonly cross_cutting_themes: components["schemas"]["CatalogTheme"][];
            readonly contents: components["schemas"]["CatalogContent"][];
            readonly group: components["schemas"]["CatalogGroup"];
            readonly teacher: components["schemas"]["CatalogTeacher"];
        };
        /**
         * @description Write contract of `POST /api/lesson-plans/`.
         *
         *     Every curriculum value arrives as an official catalog id — free text is
         *     only accepted for the teacher's own prose (`theme`, `context_diagnosis`).
         *     `campo` and `grade` are deliberately absent: the server derives them from
         *     the resolved field and the group, so a client that sends them is ignored.
         *
         *     All catalog rules live in `validate()` rather than in per-field
         *     `validate_<name>` hooks because every one of them is answerable only once
         *     `field_id` is known, and DRF does not order field-level hooks.
         */
        LessonPlanCreate: {
            group: number;
            field_id: string;
            /** @default  */
            subject_id: string;
            methodology_id: string;
            theme: string;
            context_diagnosis: string;
            scenario: components["schemas"]["ScenarioEnum"];
            duration_weeks: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            cross_cutting_theme_ids: string[];
            content_selections: components["schemas"]["ContentSelection"][];
        };
        /**
         * @description * `preescolar` - Preescolar
         *     * `primaria` - Primaria
         *     * `secundaria` - Secundaria
         * @enum {string}
         */
        LevelEnum: "preescolar" | "primaria" | "secundaria";
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description One row per caller membership (workspaces spec — "Workspace-List
         *     Endpoint Returns Only the Caller's Memberships").
         */
        MembershipList: {
            /** Format: uuid */
            id: string;
            name: string;
            type: string;
            role: components["schemas"]["MembershipListRoleEnum"];
        };
        /**
         * @description * `owner` - Owner
         *     * `admin` - Admin
         *     * `member` - Member
         * @enum {string}
         */
        MembershipListRoleEnum: "owner" | "admin" | "member";
        Message: {
            /** Format: uuid */
            readonly id: string;
            readonly role: components["schemas"]["MessageRoleEnum"];
            readonly content: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `user` - User
         *     * `assistant` - Assistant
         * @enum {string}
         */
        MessageRoleEnum: "user" | "assistant";
        PatchedConversationRename: {
            title?: string;
        };
        PatchedGroup: {
            readonly id?: number;
            school_year?: number;
            grado?: number;
            grupo?: string;
            /** Format: uuid */
            readonly workspace?: string;
        };
        PatchedSchool: {
            readonly id?: number;
            name?: string;
            cct?: string;
            level?: components["schemas"]["LevelEnum"];
            /** Format: uuid */
            readonly workspace?: string;
        };
        PatchedSchoolYear: {
            readonly id?: number;
            school?: number;
            label?: string;
            /** Format: uuid */
            readonly workspace?: string;
        };
        PatchedStudent: {
            readonly id?: number;
            group?: number;
            first_name?: string;
            last_name_paternal?: string;
            last_name_maternal?: string;
            curp?: string;
            /** Format: uuid */
            readonly workspace?: string;
        };
        /** @description One entry of the frozen persona registry, as shown in the picker. */
        Persona: {
            readonly key: string;
            readonly label: string;
            readonly description: string;
            readonly features: string[];
        };
        /**
         * @description * `teacher_minimal` - teacher_minimal
         *     * `teacher_full` - teacher_full
         *     * `quota_exhausted` - quota_exhausted
         *     * `showcase` - showcase
         * @enum {string}
         */
        PersonaEnum: "teacher_minimal" | "teacher_full" | "quota_exhausted" | "showcase";
        QuizzyChatRequest: {
            message: string;
            agent_id?: string | null;
            /** Format: uuid */
            conversation_id?: string | null;
            group_id?: number | null;
        };
        QuizzyChatResponse: {
            reply: string;
            agent_id: string;
            model: string;
            /** Format: uuid */
            conversation_id: string;
        };
        /**
         * @description * `classroom` - Classroom
         *     * `school` - School
         *     * `community` - Community
         * @enum {string}
         */
        ScenarioEnum: "classroom" | "school" | "community";
        School: {
            readonly id: number;
            name: string;
            cct?: string;
            level: components["schemas"]["LevelEnum"];
            /** Format: uuid */
            readonly workspace: string;
        };
        SchoolYear: {
            readonly id: number;
            school: number;
            label: string;
            /** Format: uuid */
            readonly workspace: string;
        };
        /**
         * @description * `present` - Present
         *     * `absent` - Absent
         *     * `late` - Late
         *     * `excused` - Excused
         * @enum {string}
         */
        Status148Enum: "present" | "absent" | "late" | "excused";
        /**
         * @description * `pending` - Pending
         *     * `ready` - Ready
         *     * `failed` - Failed
         * @enum {string}
         */
        Status95aEnum: "pending" | "ready" | "failed";
        Student: {
            readonly id: number;
            group: number;
            first_name: string;
            last_name_paternal: string;
            last_name_maternal?: string;
            curp?: string;
            /** Format: uuid */
            readonly workspace: string;
        };
        User: {
            readonly id: number;
            /** Format: email */
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attendance_bulk_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceBulkRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AttendanceBulkRequest"];
                "multipart/form-data": components["schemas"]["AttendanceBulkRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceBulkResponse"];
                };
            };
        };
    };
    attendance_roster_list: {
        parameters: {
            query: {
                date: string;
                group: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRosterEntry"][];
                };
            };
        };
    };
    attendance_week_retrieve: {
        parameters: {
            query: {
                group: number;
                week_start: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceWeekResponse"];
                };
            };
        };
    };
    attendance_week_bulk_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceWeekBulkRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AttendanceWeekBulkRequest"];
                "multipart/form-data": components["schemas"]["AttendanceWeekBulkRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceBulkResponse"];
                };
            };
        };
    };
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    demo_personas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"][];
                };
            };
        };
    };
    demo_sessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoSessionCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["DemoSessionCreate"];
                "multipart/form-data": components["schemas"]["DemoSessionCreate"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSession"];
                };
            };
        };
    };
    demo_sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSession"];
                };
            };
        };
    };
    groups_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    groups_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Group"];
                "application/x-www-form-urlencoded": components["schemas"]["Group"];
                "multipart/form-data": components["schemas"]["Group"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    groups_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    groups_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Group"];
                "application/x-www-form-urlencoded": components["schemas"]["Group"];
                "multipart/form-data": components["schemas"]["Group"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    groups_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    groups_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this group. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGroup"];
                "multipart/form-data": components["schemas"]["PatchedGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lesson_plans_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"][];
                };
            };
        };
    };
    lesson_plans_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonPlanCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonPlanCreate"];
                "multipart/form-data": components["schemas"]["LessonPlanCreate"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    lesson_plans_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"];
                };
            };
        };
    };
    lesson_plans_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lesson_plans_export_retrieve: {
        parameters: {
            query?: {
                /** @description Export format; defaults to docx. */
                format?: "docx" | "md";
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this lesson plan. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                    "text/markdown": string;
                };
            };
        };
    };
    lesson_plans_catalog_retrieve: {
        parameters: {
            query: {
                /** @description Id of the formative field whose catalog is requested. */
                field: string;
                /** @description Id of the secondary-school group being planned for. */
                group: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlanCatalog"];
                };
            };
        };
    };
    lesson_plans_fields_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogField"][];
                };
            };
        };
    };
    lesson_plans_quota_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationQuota"];
                };
            };
        };
    };
    quizzy_chat_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizzyChatRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["QuizzyChatRequest"];
                "multipart/form-data": components["schemas"]["QuizzyChatRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizzyChatResponse"];
                };
            };
        };
    };
    quizzy_conversations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationList"][];
                };
            };
        };
    };
    quizzy_conversations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
        };
    };
    quizzy_conversations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    quizzy_conversations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedConversationRename"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedConversationRename"];
                "multipart/form-data": components["schemas"]["PatchedConversationRename"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationList"];
                };
            };
        };
    };
    school_years_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYear"][];
                };
            };
        };
    };
    school_years_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchoolYear"];
                "application/x-www-form-urlencoded": components["schemas"]["SchoolYear"];
                "multipart/form-data": components["schemas"]["SchoolYear"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYear"];
                };
            };
        };
    };
    school_years_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this school year. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYear"];
                };
            };
        };
    };
    school_years_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this school year. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchoolYear"];
                "application/x-www-form-urlencoded": components["schemas"]["SchoolYear"];
                "multipart/form-data": components["schemas"]["SchoolYear"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYear"];
                };
            };
        };
    };
    school_years_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this school year. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    school_years_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this school year. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSchoolYear"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSchoolYear"];
                "multipart/form-data": components["schemas"]["PatchedSchoolYear"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYear"];
                };
            };
        };
    };
    schools_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"][];
                };
            };
        };
    };
    schools_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["School"];
                "application/x-www-form-urlencoded": components["schemas"]["School"];
                "multipart/form-data": components["schemas"]["School"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    schools_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this school. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    schools_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this school. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["School"];
                "application/x-www-form-urlencoded": components["schemas"]["School"];
                "multipart/form-data": components["schemas"]["School"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    schools_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this school. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schools_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this school. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSchool"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSchool"];
                "multipart/form-data": components["schemas"]["PatchedSchool"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    students_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"][];
                };
            };
        };
    };
    students_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Student"];
                "application/x-www-form-urlencoded": components["schemas"]["Student"];
                "multipart/form-data": components["schemas"]["Student"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Student"];
                "application/x-www-form-urlencoded": components["schemas"]["Student"];
                "multipart/form-data": components["schemas"]["Student"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    students_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    students_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this student. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStudent"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStudent"];
                "multipart/form-data": components["schemas"]["PatchedStudent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"];
                };
            };
        };
    };
    workspaces_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipList"][];
                };
            };
        };
    };
}
