# Generated by Django 6.0.7 on 2026-07-22 18:52
#
# WorkspaceInvitation is intentionally NOT appended to 0003_rls.py's
# SCOPED_TABLES: it is a plain-FK model, not a ScopedModel, and MUST stay
# outside RLS so an invitee can reach their own invite by token before they
# have any active-workspace context (invitations spec — RLS Exclusion).
# Do not "fix" this by adding the table to SCOPED_TABLES.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_rls_fix_empty_setting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspaces_workspaceinvitation",
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="workspaces__workspa_bea08e_idx",
                    ),
                    models.Index(
                        fields=["email", "status"], name="workspaces__email_efe80b_idx"
                    ),
                ],
            },
        ),
    ]
