# Generated by Django 6.0.7 on 2026-07-22 20:22
#
# WorkspaceHistory is intentionally NOT appended to 0003_rls.py's
# SCOPED_TABLES: a `moved` row references two distinct workspaces in one
# INSERT, but the tenancy middleware sets exactly one `app.workspace_id` per
# transaction, so a single-workspace RLS `WITH CHECK` can never be satisfied
# for a row that legitimately spans two workspaces (workspace-history spec —
# RLS Exclusion). Do not "fix" this by adding the table to SCOPED_TABLES.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_workspaceinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("moved", "Moved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_workspace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_from",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_workspace",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_to",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspaces_workspacehistory",
            },
        ),
    ]
