# Generated by Django 6.0.7 on 2026-07-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0006_workspacehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
