# Generated by Django 6.0.7 on 2026-07-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_plans", "0002_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonplan",
            name="content_selections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="context_diagnosis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="cross_cutting_theme_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="duration_weeks",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="field_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="methodology_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="scenario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("classroom", "Classroom"),
                    ("school", "School"),
                    ("community", "Community"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="subject_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
