# Generated by Django 6.0.7 on 2026-07-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_plans", "0003_project_context"),
        ("workspaces", "0007_workspace_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_plans_generationusage",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "period"),
                        name="unique_workspace_generation_period",
                    )
                ],
            },
        ),
    ]
