# Generated by Django 6.0.7 on 2026-07-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_plans", "0005_generationusage_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonplan",
            name="grounding_selections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="invented_pda_texts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
